CREATE TABLE IF NOT EXISTS player(
 id INT PRIMARY KEY,
 playerName VARCHAR(20) NOT NULL,
 age INT NOT NULL,
 playerType VARCHAR(40) NOT NULL,
 rating INT  NOT NULL,
 create_time TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
 update_time TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

